from .default_menu import get_default_menu_inline_markup
from .themes_menu import get_themes_menu_inline_markup
from .back_default_menu import get_back_to_menu_inline_markup
from .choice_yes_or_no_menu import get_choice_yes_or_no_menu_inline_markup
from .link_btn import get_link_inline_markup
from .admin_panel import get_admin_panel_inline_markup
